---
apiVersion: v1
kind: Namespace
metadata:
  name: prometheus-blackbox-exporter
  labels:
    toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: prometheus-blackbox-exporter
spec:
  interval: 24h
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: prometheus-blackbox-exporter
  namespace: prometheus-blackbox-exporter
spec:
  interval: 30m
  chart:
    spec:
      chart: prometheus-blackbox-exporter
      version: "v0.24.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: prometheus-blackbox-exporter
      interval: 12h

